version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: clinica
      POSTGRES_USER: clinica
      POSTGRES_PASSWORD: clinica
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql